const PROJECT_STAGE = {
  DOCUMENTATION: 'DOCUMENTATION',
  APPLICATION_FILED: 'APPLICATION_FILED',
  SCRUTINY: 'SCRUTINY',
  CLARIFICATIONS: 'CLARIFICATIONS',
  APPROVED: 'APPROVED',
  DISBURSED: 'DISBURSED',
  REJECTED: 'REJECTED',
  ON_HOLD: 'ON_HOLD',
  COMPLETED: 'COMPLETED'
};

module.exports = { PROJECT_STAGE };
